### PR TITLE
Region names with iso 3166 2 code

### PR DESCRIPTION
**Pull request by erik55**
There are more than the ones already mentioned in the description. And some have both country and subdivision codes. This is important to know, as country codes are preferred by the code.

### CODE REVIEW

**Comment by westnordost** [comment]
But it does not include **all** subdivisions for these countries, right? Only for US, CA, IN, CN, AU it includes **all** subdivisions.

**Comment by erik55** [comment]
As of https://en.wikipedia.org/wiki/ISO_3166-2 what you say seems to be correct. Still the sentence “The data set includes subdivisions only for” is not correct, as it also includes some more (seemingly remote) subdivisions. But maybe that is not relevant. For me it was, for the case of the Canary Islands. The phrase could be changed to

> The data set contains all subdivisions for …, and also some remote subdivisions.

**Comment by westnordost** [comment]
Ok, or 
> The data set contains all subdivisions for …, plus a few subdivisions for other countries. See the source file for details

Those don't necessarily need to be remote. IIRC the Krim is also included in order to tell it apart from the (rest of the) Ukraine.

**Comment by erik55** [comment]
Great.

**Pull request closed without merging**
